load("@buildifier_prebuilt//:rules.bzl", "buildifier")

package(default_visibility = ["//visibility:public"])

# Format every Starlark / BUILD file in the workspace. Run with
# `bazel run //tools:buildifier`.
buildifier(
    name = "buildifier",
)

alias(
    name = "make_entry",
    actual = "//tools/make_entry",
)

exports_files(["presubmit.yml"])
